import { Navbar } from "./_components/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={"h-full"}>
      <Navbar />
      {children}
    </div>
  );
}
